### ISSUE TITLE
How to retrieve the actual value of an string resource

### ISSUE THREAD

**Issue by xingrz** [openstf/adbkit-apkreader#1]
Hi,

I noticed that this module just parse the AndroidManifest.xml and leave those string values as `resourceId:XXXX`s. Could you tell me how to retrieve the actual value of these resource ids? Thanks.

**Comment by LegNeato** [comment]
I don't think this is possible, as the values are compiled in `resources.arsc` and this library doesn't know how to read and decode that AFAICT.

**Comment by sorccu** [comment]
That is correct. They were not needed for our use case, so they were never
implemented. I would be very happy to accept a PR, though.

**Comment by imquincychen** [comment]
Maybe you can try this one: https://github.com/chenquincy/app-info-parser
