### ISSUE TITLE
Parsing AndroidManifest.xml error if there is no namespace in xml.

### ISSUE THREAD

**Issue by zr0827** [openstf/adbkit-apkreader#14]
Apk-reader raises error when I try to use it to parse Chrome 68 beta apk.  By further investgation, I find that there is no namespace declaration in manifest.xml. The apk-reader seems to assume that it must be namespace in manifest.xml, which causes the error. I don't know chrome is intentional or not. However, I think it is better to make it compatible. I check the Chrome project, such as catapult project. They use aapt tool to dump xml to get the activity. They make it compatible by adding the correct namespace before parsing it.

**Comment by sorccu** [comment]
You're right, removing [this line](https://github.com/openstf/adbkit-apkreader/blob/848da75313c31ebfe4ea987c5e4e2416ef251638/lib/apkreader/parser/binaryxml.js#L526) makes it work. Seems like we should check the chunk type instead of just assuming it's going to be there.

**Comment by sorccu** [comment]
See the https://github.com/openstf/adbkit-apkreader/tree/issue-14 branch. Try it out and see whether it works for you.

**Comment by sorccu** [comment]
Released as 3.0.2.
