### ISSUE TITLE
adbkit-apkreader getting wrong fields from AndroidManifest

### ISSUE THREAD

**Issue by IvoVentura** [openstf/adbkit-apkreader#17]
Good morning,

We are having issues with this plugin, it is reading the information of the AndroidManifest.xml incorrectly.

Instead of grabbing the package name it's grabbing the platformBuildVersionName instead.

We have an open issue on the google-play-vsts-extension regarding this issue. You have on there the manifest we are using plus the execution result of the adbkit-apkreader.

- https://github.com/Microsoft/google-play-vsts-extension/issues/106#issuecomment-424424331

Best Regards

**Comment by sorccu** [comment]
I need the APK file, or you can extract and send just the binary manifest from the .apk file. If you can also provide the XML manifest, that would be great. Note though that the XML manifest is not enough by itself, I really need the binary version too. Email to simo at openstf dot io.

**Comment by IvoVentura** [comment]
Hi @sorccu,

I'll send you the apk and xml via email.

Thanks for the help,
Best Regards

**Comment by sorccu** [comment]
Should be fixed now in v3.1.0. The issue was the the manifest's string pool referred to the same string a few times, which confused the string parser. Haven't encountered that behavior before.
