### ISSUE TITLE
Is it possible to use apkreader with browserify?

### ISSUE THREAD

**Issue by twmht** [openstf/adbkit-apkreader#2]
main.js

```
var util = require('util')
var ApkReader = require('adbkit-apkreader')

var reader = ApkReader.readFile('test.apk')
var manifest = reader.readManifestSync()

console.log(util.inspect(manifest, { depth: null }))
```

```
browserify main.js
```

will produce

```

Error: Cannot find module './src/apkreader' from '/home/tumh/browserify/node_modules/adbkit-apkreader'
    at /home/tumh/.nvm/versions/node/v0.12.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/tumh/.nvm/versions/node/v0.12.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/tumh/.nvm/versions/node/v0.12.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/tumh/.nvm/versions/node/v0.12.1/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:99:15)
```

**Comment by sorccu** [comment]
Browserify is a bit too greedy with `require()`. For now you should be able to circumvent the problem by using `require('adbkit-apkreader/lib/apkreader')` instead.

**Comment by twmht** [comment]
cool! it works! Can you explain why browserify complains with ```require(adbkit-apkreader)```? And how did you know I should use ```require('adbkit-apkreader/lib/apkreader')``` instead?

**Comment by sorccu** [comment]
It's because our [main file](https://github.com/openstf/adbkit-apkreader/blob/develop/index.coffee) checks its own file extension on runtime, and decides whether to use the coffee source or the compiled JavaScript source. This works with regular node since we only publish the compiled JavaScript source to NPM (i.e. `index.coffee` gets published as `index.js`), and node is able to execute `require()` on runtime.

Because browserify has to include all requires in the client side package, and isn't clever enough to solve the `if` branch at compile time, it discards the `if` statement entirely and attempts to include both source trees. Then you get this failure.

I'll try to think of some other way in the future (or if someone else has any ideas, I'm interested). Eventually we're hoping to replace our CoffeeScript source with plain JavaScript, though.

**Comment by twmht** [comment]
cool! Thanks for your great explanation:)

I got other problem here.

Without browserify

main.js
```
var util = require('util')
var ApkReader = require('adbkit-apkreader')

var reader = ApkReader.readFile('test.apk')
var manifest = reader.readManifestSync()

console.log(util.inspect(manifest, { depth: null }))
```

it works with ```node main.js```.

With browserify

main.js
```
var util = require('util')
var ApkReader = require('adbkit-apkreader/lib/apkreader')

var reader = ApkReader.readFile('test.apk')
var manifest = reader.readManifestSync()

console.log(util.inspect(manifest, { depth: null }))
```

```browserify main.js -o reader.js```

But it will failed with ```node reader.js```

```
/home/tumh/browserify/apkreader.js:11882
          throw err;
                ^
TypeError: undefined is not a function
    at new module.exports (/home/tumh/browserify/apkreader.js:12645:16)
    at new ApkReader (/home/tumh/browserify/apkreader.js:11876:20)
    at Function.ApkReader.readFile (/home/tumh/browserify/apkreader.js:11869:14)
    at Object.adbkit-apkreader/lib/apkreader (/home/tumh/browserify/apkreader.js:11848:24)
    at s (/home/tumh/browserify/apkreader.js:1:316)
    at e (/home/tumh/browserify/apkreader.js:1:487)
    at Object.<anonymous> (/home/tumh/browserify/apkreader.js:1:505)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by mingyuan-xia** [comment]
Same here with `webpack`.
What about having an `index.js` that requires the js code and `index.coffee` that requires the coffee code, both at the top-level directory.
Then we can remove compiling `index.coffee` in the gulp config file.
For publishing, simply, `lib` and the `index.js` would be uploaded.
For dev, coffee remains.
After all, the index script is just to find the right main body.

**Comment by sorccu** [comment]
Well, I just spent an hour removing CoffeeScript entirely. Try version 3.0.0. Note that it may not work in older browsers as-is.

**Comment by mingyuan-xia** [comment]
work like a charm, thanks.
