### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by id0Sch** [openstf/adbkit-apkreader#5]
hi,
is this still maintained?

**Comment by sorccu** [comment]
It works, so there hasn't been a need to change anything. What do you want?

**Comment by id0Sch** [comment]
I have 2 problems actually -
- adm-zip is throwing an error for some apks
- I need to extract the supported architectures and i was wondering if i should expand this package and submit a PR or just my own fork.

**Comment by sorccu** [comment]
Pull requests are very welcome, and collaborator access is possible as well once we get to know you a little better!

**Comment by sorccu** [comment]
I will close this issue now, but please feel free to create separate issues and/or PRs for the issues you mentioned. Getting rid of `adm-zip` would be great if you know something better (it's been a while).

**Comment by id0Sch** [comment]
there's jsZip.
i will submit a PR for the archs info as it's my top priority

Thanks!
